//===========================================================================
//content1的增删改查
//获取所有数据，保存列表数据，保存三个下拉框数据
export const CONTENT1_GET_INFO_ACTION = 'CONTENT1_GET_INFO_ACTION'
export const CONTENT1_GET_OTHER_INFO_ACTION = 'CONTENT1_GET_OTHER_INFO_ACTION'
export const CONTENT1_SAVE_LIST = 'CONTENT1_SAVE_LIST'
export const CONTENT1_SAVE_CLASSIFY = 'CONTENT1_SAVE_CLASSIFY'
export const CONTENT1_SAVE_AREA = 'CONTENT1_SAVE_AREA'
export const CONTENT1_SAVE_TEAM = 'CONTENT1_SAVE_TEAM'
//添加和确认添加
export const CONTENT1_ADD_INFO_ACTION = 'CONTENT1_ADD_INFO_ACTION'
export const CONTENT1_ADD_INFO = 'CONTENT1_ADD_INFO'
export const CONTENT1_CONFIRM_ADD_INFO_ACTION = 'CONTENT1_CONFIRM_ADD_INFO_ACTION'
export const CONTENT1_CONFIRM_ADD_INFO = 'CONTENT1_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT1_EDIT_INFO_ACTION = 'CONTENT1_EDIT_INFO_ACTION'
export const CONTENT1_EDIT_INFO = 'CONTENT1_EDIT_INFO'
export const CONTENT1_CONFIRM_EDIT_INFO_ACTION = 'CONTENT1_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT1_CONFIRM_EDIT_INFO = 'CONTENT1_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT1_CONFIRM_DELETE_INFO_ACTION = 'CONTENT1_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT1_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT1_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT1_CONFIRM_CANCEL_INFO = 'CONTENT1_CONFIRM_CANCEL_INFO'


//===========================================================================
//content2的增删改查
//获取所有数据，保存列表数据，保存一个下拉框数据
export const CONTENT2_GET_INFO_ACTION = 'CONTENT2_GET_INFO_ACTION'
export const CONTENT2_GET_OTHER_INFO_ACTION = 'CONTENT2_GET_OTHER_INFO_ACTION'
export const CONTENT2_SAVE_LIST = 'CONTENT2_SAVE_LIST'
export const CONTENT2_SAVE_AREA = 'CONTENT2_SAVE_AREA'
//添加和确认添加
export const CONTENT2_ADD_INFO_ACTION = 'CONTENT2_ADD_INFO_ACTION'
export const CONTENT2_ADD_INFO = 'CONTENT2_ADD_INFO'
export const CONTENT2_CONFIRM_ADD_INFO_ACTION = 'CONTENT2_CONFIRM_ADD_INFO_ACTION'
export const CONTENT2_CONFIRM_ADD_INFO = 'CONTENT2_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT2_EDIT_INFO_ACTION = 'CONTENT2_EDIT_INFO_ACTION'
export const CONTENT2_EDIT_INFO = 'CONTENT2_EDIT_INFO'
export const CONTENT2_CONFIRM_EDIT_INFO_ACTION = 'CONTENT2_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT2_CONFIRM_EDIT_INFO = 'CONTENT2_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT2_CONFIRM_DELETE_INFO_ACTION = 'CONTENT2_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT2_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT2_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT2_CONFIRM_CANCEL_INFO = 'CONTENT2_CONFIRM_CANCEL_INFO'

//===========================================================================
//content3的增删改查
export const CONTENT3_GET_INFO_ACTION = 'CONTENT3_GET_INFO_ACTION'
export const CONTENT3_SAVE_LIST = 'CONTENT3_SAVE_LIST'
//添加和确认添加
export const CONTENT3_ADD_INFO_ACTION = 'CONTENT3_ADD_INFO_ACTION'
export const CONTENT3_ADD_INFO = 'CONTENT3_ADD_INFO'
export const CONTENT3_CONFIRM_ADD_INFO_ACTION = 'CONTENT3_CONFIRM_ADD_INFO_ACTION'
export const CONTENT3_CONFIRM_ADD_INFO = 'CONTENT3_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT3_EDIT_INFO_ACTION = 'CONTENT3_EDIT_INFO_ACTION'
export const CONTENT3_EDIT_INFO = 'CONTENT3_EDIT_INFO'
export const CONTENT3_CONFIRM_EDIT_INFO_ACTION = 'CONTENT3_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT3_CONFIRM_EDIT_INFO = 'CONTENT3_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT3_CONFIRM_DELETE_INFO_ACTION = 'CONTENT3_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT3_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT3_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT3_CONFIRM_CANCEL_INFO = 'CONTENT3_CONFIRM_CANCEL_INFO'

//===========================================================================
//content4的增删改查
export const CONTENT4_GET_INFO_ACTION = 'CONTENT4_GET_INFO_ACTION'
export const CONTENT4_SAVE_LIST = 'CONTENT4_SAVE_LIST'
//添加和确认添加
export const CONTENT4_ADD_INFO_ACTION = 'CONTENT4_ADD_INFO_ACTION'
export const CONTENT4_ADD_INFO = 'CONTENT4_ADD_INFO'
export const CONTENT4_CONFIRM_ADD_INFO_ACTION = 'CONTENT4_CONFIRM_ADD_INFO_ACTION'
export const CONTENT4_CONFIRM_ADD_INFO = 'CONTENT4_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT4_EDIT_INFO_ACTION = 'CONTENT4_EDIT_INFO_ACTION'
export const CONTENT4_EDIT_INFO = 'CONTENT4_EDIT_INFO'
export const CONTENT4_CONFIRM_EDIT_INFO_ACTION = 'CONTENT4_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT4_CONFIRM_EDIT_INFO = 'CONTENT4_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT4_CONFIRM_DELETE_INFO_ACTION = 'CONTENT4_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT4_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT4_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT4_CONFIRM_CANCEL_INFO = 'CONTENT4_CONFIRM_CANCEL_INFO'

//===========================================================================
//content5的增删改查
export const CONTENT5_GET_INFO_ACTION = 'CONTENT5_GET_INFO_ACTION'
export const CONTENT5_GET_OTHER_INFO_ACTION = 'CONTENT5_GET_OTHER_INFO_ACTION'
export const CONTENT5_SAVE_LIST = 'CONTENT5_SAVE_LIST'
export const CONTENT5_SAVE_CLASSIFY = 'CONTENT5_SAVE_CLASSIFY'
//添加和确认添加
export const CONTENT5_ADD_INFO_ACTION = 'CONTENT5_ADD_INFO_ACTION'
export const CONTENT5_ADD_INFO = 'CONTENT5_ADD_INFO'
export const CONTENT5_CONFIRM_ADD_INFO_ACTION = 'CONTENT5_CONFIRM_ADD_INFO_ACTION'
export const CONTENT5_CONFIRM_ADD_INFO = 'CONTENT5_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT5_EDIT_INFO_ACTION = 'CONTENT5_EDIT_INFO_ACTION'
export const CONTENT5_EDIT_INFO = 'CONTENT5_EDIT_INFO'
export const CONTENT5_CONFIRM_EDIT_INFO_ACTION = 'CONTENT5_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT5_CONFIRM_EDIT_INFO = 'CONTENT5_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT5_CONFIRM_DELETE_INFO_ACTION = 'CONTENT5_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT5_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT5_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT5_CONFIRM_CANCEL_INFO = 'CONTENT5_CONFIRM_CANCEL_INFO'


//===========================================================================
//content6的增删改查
export const CONTENT6_GET_INFO_ACTION = 'CONTENT6_GET_INFO_ACTION'
export const CONTENT6_SAVE_LIST = 'CONTENT6_SAVE_LIST'
//添加和确认添加
export const CONTENT6_ADD_INFO_ACTION = 'CONTENT6_ADD_INFO_ACTION'
export const CONTENT6_ADD_INFO = 'CONTENT6_ADD_INFO'
export const CONTENT6_CONFIRM_ADD_INFO_ACTION = 'CONTENT6_CONFIRM_ADD_INFO_ACTION'
export const CONTENT6_CONFIRM_ADD_INFO = 'CONTENT6_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT6_EDIT_INFO_ACTION = 'CONTENT6_EDIT_INFO_ACTION'
export const CONTENT6_EDIT_INFO = 'CONTENT6_EDIT_INFO'
export const CONTENT6_CONFIRM_EDIT_INFO_ACTION = 'CONTENT6_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT6_CONFIRM_EDIT_INFO = 'CONTENT6_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT6_CONFIRM_DELETE_INFO_ACTION = 'CONTENT6_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT6_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT6_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT6_CONFIRM_CANCEL_INFO = 'CONTENT6_CONFIRM_CANCEL_INFO'

//===========================================================================
//content7的增删改查
export const CONTENT7_GET_INFO_ACTION = 'CONTENT7_GET_INFO_ACTION'
export const CONTENT7_GET_OTHER_INFO_ACTION = 'CONTENT7_GET_OTHER_INFO_ACTION'
export const CONTENT7_SAVE_LIST = 'CONTENT7_SAVE_LIST'
export const CONTENT7_SAVE_SECTION = 'CONTENT7_SAVE_SECTION'
export const CONTENT7_SAVE_AREA = 'CONTENT7_SAVE_AREA'
export const CONTENT7_SAVE_SECTION_VALUE = 'CONTENT7_SAVE_SECTION_VALUE'
export const CONTENT7_SEARCH_INFO_ACTION = 'CONTENT7_SEARCH_INFO_ACTION'
//添加和确认添加
export const CONTENT7_ADD_INFO_ACTION = 'CONTENT7_ADD_INFO_ACTION'
export const CONTENT7_ADD_INFO = 'CONTENT7_ADD_INFO'
export const CONTENT7_CONFIRM_ADD_INFO_ACTION = 'CONTENT7_CONFIRM_ADD_INFO_ACTION'
export const CONTENT7_CONFIRM_ADD_INFO = 'CONTENT7_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT7_EDIT_INFO_ACTION = 'CONTENT7_EDIT_INFO_ACTION'
export const CONTENT7_EDIT_INFO = 'CONTENT7_EDIT_INFO'
export const CONTENT7_CONFIRM_EDIT_INFO_ACTION = 'CONTENT7_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT7_CONFIRM_EDIT_INFO = 'CONTENT7_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT7_CONFIRM_DELETE_INFO_ACTION = 'CONTENT7_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT7_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT7_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT7_CONFIRM_CANCEL_INFO = 'CONTENT7_CONFIRM_CANCEL_INFO'

//===========================================================================
//content8的增删改查
export const CONTENT8_GET_INFO_ACTION = 'CONTENT8_GET_INFO_ACTION'
export const CONTENT8_GET_OTHER_INFO_ACTION = 'CONTENT8_GET_OTHER_INFO_ACTION'
export const CONTENT8_GET_GROUP_INFO_ACTION = 'CONTENT8_GET_GROUP_INFO_ACTION'
export const CONTENT8_SEARCH_INFO_ACTION = 'CONTENT8_SEARCH_INFO_ACTION'
export const CONTENT8_SAVE_LIST = 'CONTENT8_SAVE_LIST'
export const CONTENT8_SAVE_AREA = 'CONTENT8_SAVE_AREA'
export const CONTENT8_SAVE_SECTION = 'CONTENT8_SAVE_SECTION'
export const CONTENT8_SAVE_GROUP_SEARCH = 'CONTENT8_SAVE_GROUP_SEARCH'
export const CONTENT8_SAVE_GROUP = 'CONTENT8_SAVE_GROUP'
export const CONTENT8_SAVE_SECTION_VALUE = 'CONTENT8_SAVE_SECTION_VALUE'
export const CONTENT8_SAVE_GROUP_VALUE = 'CONTENT8_SAVE_GROUP_VALUE'
//添加和确认添加
export const CONTENT8_ADD_INFO_ACTION = 'CONTENT8_ADD_INFO_ACTION'
export const CONTENT8_ADD_INFO = 'CONTENT8_ADD_INFO'
export const CONTENT8_CONFIRM_ADD_INFO_ACTION = 'CONTENT8_CONFIRM_ADD_INFO_ACTION'
export const CONTENT8_CONFIRM_ADD_INFO = 'CONTENT8_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT8_EDIT_INFO_ACTION = 'CONTENT8_EDIT_INFO_ACTION'
export const CONTENT8_EDIT_INFO = 'CONTENT8_EDIT_INFO'
export const CONTENT8_CONFIRM_EDIT_INFO_ACTION = 'CONTENT8_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT8_CONFIRM_EDIT_INFO = 'CONTENT8_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT8_CONFIRM_DELETE_INFO_ACTION = 'CONTENT8_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT8_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT8_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT8_CONFIRM_CANCEL_INFO = 'CONTENT8_CONFIRM_CANCEL_INFO'

//===========================================================================
//content9的增删改查
export const CONTENT9_GET_OTHER_INFO_ACTION = 'CONTENT9_GET_OTHER_INFO_ACTION'
//table
//获取数据
export const CONTENT9_GET_TABLE_INFO_ACTION = 'CONTENT9_GET_TABLE_INFO_ACTION'
export const CONTENT9_SAVE_TABLE_INFO = 'CONTENT9_SAVE_TABLE_INFO'
export const CONTENT9_SAVE_TABLE_SELECT_INFO = 'CONTENT9_SAVE_TABLE_SELECT_INFO'
//添加操作，编辑操作
export const CONTENT9_TABLE_ADD_INFO = 'CONTENT9_TABLE_ADD_INFO'
export const CONTENT9_TABLE_EDIT_INFO = 'CONTENT9_TABLE_EDIT_INFO'
//确认添加操作，确认加添
export const CONTENT9_TABLE_CONFIRM_ADD_INFO_ACTION = 'CONTENT9_TABLE_CONFIRM_ADD_INFO_ACTION'
export const CONTENT9_TABLE_CONFIRM_ADD_INFO = 'CONTENT9_TABLE_CONFIRM_ADD_INFO'
//确认添加编辑，确认编辑
export const CONTENT9_TABLE_CONFIRM_EDIT_INFO_ACTION = 'CONTENT9_TABLE_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT9_TABLE_CONFIRM_EDIT_INFO = 'CONTENT9_TABLE_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT9_TABLE_CONFIRM_DELETE_INFO_ACTION = 'CONTENT9_TABLE_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT9_TABLE_CONFIRM_CANCEL_INFO = 'CONTENT9_TABLE_CONFIRM_CANCEL_INFO'
//list
//获取数据
export const CONTENT9_GET_LIST_INFO_ACTION = 'CONTENT9_GET_LIST_INFO_ACTION'
export const CONTENT9_SAVE_LIST_INFO = 'CONTENT9_SAVE_LIST_INFO'
//添加操作，编辑操作
export const CONTENT9_LIST_ADD_INFO = 'CONTENT9_LIST_ADD_INFO'
export const CONTENT9_LIST_EDIT_INFO = 'CONTENT9_LIST_EDIT_INFO'
//确认添加操作，确认加添
export const CONTENT9_LIST_CONFIRM_ADD_INFO_ACTION = 'CONTENT9_LIST_CONFIRM_ADD_INFO_ACTION'
export const CONTENT9_LIST_CONFIRM_ADD_INFO = 'CONTENT9_LIST_CONFIRM_ADD_INFO'
//确认添加编辑，确认编辑
export const CONTENT9_LIST_CONFIRM_EDIT_INFO_ACTION = 'CONTENT9_LIST_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT9_LIST_CONFIRM_EDIT_INFO = 'CONTENT9_LIST_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT9_LIST_CONFIRM_DELETE_INFO_ACTION = 'CONTENT9_LIST_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT9_LIST_CONFIRM_CANCEL_INFO = 'CONTENT9_LIST_CONFIRM_CANCEL_INFO'

//===========================================================================
//content10-1的增删改查
export const CONTENT10_1_GET_INFO_ACTION = 'CONTENT10_1_GET_INFO_ACTION'
export const CONTENT10_1_GET_OTHER_INFO_ACTION = 'CONTENT10_1_GET_OTHER_INFO_ACTION'
export const CONTENT10_1_SAVE_LIST = 'CONTENT10_1_SAVE_LIST'
export const CONTENT10_1_SAVE_AREA = 'CONTENT10_1_SAVE_AREA'
//添加和确认添加
export const CONTENT10_1_ADD_INFO_ACTION = 'CONTENT10_1_ADD_INFO_ACTION'
export const CONTENT10_1_ADD_INFO = 'CONTENT10_1_ADD_INFO'
export const CONTENT10_1_CONFIRM_ADD_INFO_ACTION = 'CONTENT10_1_CONFIRM_ADD_INFO_ACTION'
export const CONTENT10_1_CONFIRM_ADD_INFO = 'CONTENT10_1_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT10_1_EDIT_INFO_ACTION = 'CONTENT10_1_EDIT_INFO_ACTION'
export const CONTENT10_1_EDIT_INFO = 'CONTENT10_1_EDIT_INFO'
export const CONTENT10_1_CONFIRM_EDIT_INFO_ACTION = 'CONTENT10_1_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT10_1_CONFIRM_EDIT_INFO = 'CONTENT10_1_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT10_1_CONFIRM_DELETE_INFO_ACTION = 'CONTENT10_1_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT10_1_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT10_1_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT10_1_CONFIRM_CANCEL_INFO = 'CONTENT10_1_CONFIRM_CANCEL_INFO'

//===========================================================================
//content11-1的增删改查
export const CONTENT11_1_GET_INFO_ACTION = 'CONTENT11_1_GET_INFO_ACTION'
export const CONTENT11_1_GET_OTHER_INFO_ACTION = 'CONTENT11_1_GET_OTHER_INFO_ACTION'
export const CONTENT11_1_GET_POST_INFO_ACTION = 'CONTENT11_1_GET_POST_INFO_ACTION'
export const CONTENT11_1_GET_TEAM_INFO_ACTION = 'CONTENT11_1_GET_TEAM_INFO_ACTION'
export const CONTENT11_1_SAVE_LIST = 'CONTENT11_1_SAVE_LIST'
export const CONTENT11_1_SAVE_AREA = 'CONTENT11_1_SAVE_AREA'
export const CONTENT11_1_SAVE_ORG = 'CONTENT11_1_SAVE_ORG'
export const CONTENT11_1_SAVE_POST = 'CONTENT11_1_SAVE_POST'
export const CONTENT11_1_SAVE_TEAM = 'CONTENT11_1_SAVE_TEAM'
export const CONTENT11_1_SAVE_ROLE = 'CONTENT11_1_SAVE_ROLE'
export const CONTENT11_1_UPDATE_STATUS_1 = 'CONTENT11_1_UPDATE_STATUS_1'
export const CONTENT11_1_UPDATE_STATUS_2 = 'CONTENT11_1_UPDATE_STATUS_2'
//添加和确认添加
export const CONTENT11_1_ADD_INFO_ACTION = 'CONTENT11_1_ADD_INFO_ACTION'
export const CONTENT11_1_ADD_INFO = 'CONTENT11_1_ADD_INFO'
export const CONTENT11_1_CONFIRM_ADD_INFO_ACTION = 'CONTENT11_1_CONFIRM_ADD_INFO_ACTION'
export const CONTENT11_1_CONFIRM_ADD_INFO = 'CONTENT11_1_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT11_1_EDIT_INFO_ACTION = 'CONTENT11_1_EDIT_INFO_ACTION'
export const CONTENT11_1_EDIT_INFO = 'CONTENT11_1_EDIT_INFO'
export const CONTENT11_1_CONFIRM_EDIT_INFO_ACTION = 'CONTENT11_1_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT11_1_CONFIRM_EDIT_INFO = 'CONTENT11_1_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT11_1_CONFIRM_DELETE_INFO_ACTION = 'CONTENT11_1_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT11_1_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT11_1_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT11_1_CONFIRM_CANCEL_INFO = 'CONTENT11_1_CONFIRM_CANCEL_INFO'

//===========================================================================
//content11-2的增删改查
export const CONTENT11_2_GET_INFO_ACTION = 'CONTENT11_2_GET_INFO_ACTION'
export const CONTENT11_2_GET_OTHER_INFO_ACTION = 'CONTENT11_2_GET_OTHER_INFO_ACTION'
export const CONTENT11_2_SAVE_LIST = 'CONTENT11_2_SAVE_LIST'
export const CONTENT11_2_SAVE_AREA = 'CONTENT11_2_SAVE_AREA'
export const CONTENT11_2_SAVE_USER = 'CONTENT11_2_SAVE_USER'
//添加和确认添加
export const CONTENT11_2_ADD_INFO_ACTION = 'CONTENT11_2_ADD_INFO_ACTION'
export const CONTENT11_2_ADD_INFO = 'CONTENT11_2_ADD_INFO'
export const CONTENT11_2_CONFIRM_ADD_INFO_ACTION = 'CONTENT11_2_CONFIRM_ADD_INFO_ACTION'
export const CONTENT11_2_CONFIRM_ADD_INFO = 'CONTENT11_2_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT11_2_EDIT_INFO_ACTION = 'CONTENT11_2_EDIT_INFO_ACTION'
export const CONTENT11_2_EDIT_INFO = 'CONTENT11_2_EDIT_INFO'
export const CONTENT11_2_CONFIRM_EDIT_INFO_ACTION = 'CONTENT11_2_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT11_2_CONFIRM_EDIT_INFO = 'CONTENT11_2_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT11_2_CONFIRM_DELETE_INFO_ACTION = 'CONTENT11_2_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT11_2_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT11_2_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT11_2_CONFIRM_CANCEL_INFO = 'CONTENT11_2_CONFIRM_CANCEL_INFO'

//===========================================================================
//content12的增删改查
export const CONTENT12_GET_INFO_ACTION = 'CONTENT12_GET_INFO_ACTION'
export const CONTENT12_GET_OTHER_INFO_ACTION = 'CONTENT12_GET_OTHER_INFO_ACTION'
export const CONTENT12_GET_DETAILS_ACTION = 'CONTENT12_GET_DETAILS_ACTION'
export const CONTENT12_SAVE_LIST = 'CONTENT12_SAVE_LIST'
export const CONTENT12_SAVE_TEAM = 'CONTENT12_SAVE_TEAM'
export const CONTENT12_SAVE_SPECIFIC_LIST = 'CONTENT12_SAVE_SPECIFIC_LIST'
export const CONTENT12_SAVE_PLAN = 'CONTENT12_SAVE_PLAN'
export const CONTENT12_SAVE_WAY = 'CONTENT12_SAVE_WAY'
export const CONTENT12_SAVE_SPECIFIC_WAY = 'CONTENT12_SAVE_SPECIFIC_WAY'
//添加和确认添加
export const CONTENT12_ADD_INFO_ACTION = 'CONTENT12_ADD_INFO_ACTION'
export const CONTENT12_ADD_INFO = 'CONTENT12_ADD_INFO'
export const CONTENT12_CONFIRM_ADD_INFO_ACTION = 'CONTENT12_CONFIRM_ADD_INFO_ACTION'
export const CONTENT12_CONFIRM_ADD_INFO = 'CONTENT12_CONFIRM_ADD_INFO'
export const CONTENT12_CONFIRM_ADD_SPECIFIC_WAY = 'CONTENT12_CONFIRM_ADD_SPECIFIC_WAY'
export const CONTENT12_CONFIRM_DELETE_SPECIFIC_WAY = 'CONTENT12_CONFIRM_DELETE_SPECIFIC_WAY'
//编辑和确认更改
export const CONTENT12_EDIT_INFO_ACTION = 'CONTENT12_EDIT_INFO_ACTION'
export const CONTENT12_EDIT_INFO = 'CONTENT12_EDIT_INFO'
export const CONTENT12_CONFIRM_EDIT_INFO_ACTION = 'CONTENT12_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT12_CONFIRM_EDIT_INFO = 'CONTENT12_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT12_CONFIRM_DELETE_INFO_ACTION = 'CONTENT12_CONFIRM_DELETE_INFO_ACTION'
//确认生效（执行）
export const CONTENT12_CONFIRM_EXECUTE_INFO_ACTION = 'CONTENT12_CONFIRM_EXECUTE_INFO_ACTION'
//确认失效（未执行）
export const CONTENT12_CONFIRM_NOT_EXECUTE_INFO_ACTION = 'CONTENT12_CONFIRM_NOT_EXECUTE_INFO_ACTION'
//确认取消
export const CONTENT12_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT12_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT12_CONFIRM_CANCEL_INFO = 'CONTENT12_CONFIRM_CANCEL_INFO'
export const CONTENT12_CONFIRM_DETAILS_INFO = 'CONTENT12_CONFIRM_CANCEL_DETAILS_INFO'

//===========================================================================
//content13的增删改查
//获取所有数据，保存列表数据，保存三个下拉框数据
export const CONTENT13_GET_INFO_ACTION = 'CONTENT13_GET_INFO_ACTION'
export const CONTENT13_GET_OTHER_INFO_ACTION = 'CONTENT13_GET_OTHER_INFO_ACTION'
export const CONTENT13_SET_MQ_ACTION = 'CONTENT13_SET_MQ_ACTION'
export const CONTENT13_SAVE_LIST = 'CONTENT13_SAVE_LIST'
export const CONTENT13_SAVE_AREA = 'CONTENT13_SAVE_AREA'
export const CONTENT13_SAVE_TEAM = 'CONTENT13_SAVE_TEAM'
//编辑和确认更改
export const CONTENT13_EDIT_INFO_ACTION = 'CONTENT13_EDIT_INFO_ACTION'
export const CONTENT13_EDIT_INFO = 'CONTENT13_EDIT_INFO'
export const CONTENT13_CONFIRM_EDIT_INFO_ACTION = 'CONTENT13_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT13_CONFIRM_EDIT_INFO = 'CONTENT13_CONFIRM_EDIT_INFO'
//开始检票和结束检票
export const CONTENT13_CONFIRM_CHECK_IN_INFO_ACTION = 'CONTENT13_CONFIRM_CHECK_IN_INFO_ACTION'
export const CONTENT13_CONFIRM_CHECK_END_INFO_ACTION = 'CONTENT13_CONFIRM_CHECK_END_INFO_ACTION'
//确认取消
export const CONTENT13_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT13_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT13_CONFIRM_CANCEL_INFO = 'CONTENT13_CONFIRM_CANCEL_INFO'

//===========================================================================
//content14-1的增删改查
//获取所有数据，保存列表数据，保存一个下拉框数据
export const CONTENT14_1_GET_INFO_ACTION = 'CONTENT14_1_GET_INFO_ACTION'
export const CONTENT14_1_GET_OTHER_INFO_ACTION = 'CONTENT14_1_GET_OTHER_INFO_ACTION'
export const CONTENT14_1_SAVE_LIST = 'CONTENT14_1_SAVE_LIST'
export const CONTENT14_1_SAVE_AREA = 'CONTENT14_1_SAVE_AREA'
//添加和确认添加
export const CONTENT14_1_ADD_INFO_ACTION = 'CONTENT14_1_ADD_INFO_ACTION'
export const CONTENT14_1_ADD_INFO = 'CONTENT14_1_ADD_INFO'
export const CONTENT14_1_CONFIRM_ADD_INFO_ACTION = 'CONTENT14_1_CONFIRM_ADD_INFO_ACTION'
export const CONTENT14_1_CONFIRM_ADD_INFO = 'CONTENT14_1_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT14_1_EDIT_INFO_ACTION = 'CONTENT14_1_EDIT_INFO_ACTION'
export const CONTENT14_1_EDIT_INFO = 'CONTENT14_1_EDIT_INFO'
export const CONTENT14_1_CONFIRM_EDIT_INFO_ACTION = 'CONTENT14_1_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT14_1_CONFIRM_EDIT_INFO = 'CONTENT14_1_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT14_1_CONFIRM_DELETE_INFO_ACTION = 'CONTENT14_1_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT14_1_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT14_1_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT14_1_CONFIRM_CANCEL_INFO = 'CONTENT14_1_CONFIRM_CANCEL_INFO'

//===========================================================================
//content14-2的增删改查
//获取所有数据，保存列表数据，保存一个下拉框数据
export const CONTENT14_2_GET_INFO_ACTION = 'CONTENT14_2_GET_INFO_ACTION'
export const CONTENT14_2_GET_OTHER_INFO_ACTION = 'CONTENT14_2_GET_OTHER_INFO_ACTION'
export const CONTENT14_2_SAVE_LIST = 'CONTENT14_2_SAVE_LIST'
export const CONTENT14_2_SAVE_AREA = 'CONTENT14_2_SAVE_AREA'
//添加和确认添加
export const CONTENT14_2_ADD_INFO_ACTION = 'CONTENT14_2_ADD_INFO_ACTION'
export const CONTENT14_2_ADD_INFO = 'CONTENT14_2_ADD_INFO'
export const CONTENT14_2_CONFIRM_ADD_INFO_ACTION = 'CONTENT14_2_CONFIRM_ADD_INFO_ACTION'
export const CONTENT14_2_CONFIRM_ADD_INFO = 'CONTENT14_2_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT14_2_EDIT_INFO_ACTION = 'CONTENT14_2_EDIT_INFO_ACTION'
export const CONTENT14_2_EDIT_INFO = 'CONTENT14_2_EDIT_INFO'
export const CONTENT14_2_CONFIRM_EDIT_INFO_ACTION = 'CONTENT14_2_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT14_2_CONFIRM_EDIT_INFO = 'CONTENT14_2_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT14_2_CONFIRM_DELETE_INFO_ACTION = 'CONTENT14_2_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT14_2_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT14_2_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT14_2_CONFIRM_CANCEL_INFO = 'CONTENT14_2_CONFIRM_CANCEL_INFO'


//===========================================================================
//content14-3的增删改查
//获取所有数据，保存列表数据，保存一个下拉框数据
export const CONTENT14_3_GET_INFO_ACTION = 'CONTENT14_3_GET_INFO_ACTION'
export const CONTENT14_3_GET_OTHER_INFO_ACTION = 'CONTENT14_3_GET_OTHER_INFO_ACTION'
export const CONTENT14_3_SAVE_LIST = 'CONTENT14_3_SAVE_LIST'
export const CONTENT14_3_SAVE_AREA = 'CONTENT14_3_SAVE_AREA'
//添加和确认添加
export const CONTENT14_3_ADD_INFO_ACTION = 'CONTENT14_3_ADD_INFO_ACTION'
export const CONTENT14_3_ADD_INFO = 'CONTENT14_3_ADD_INFO'
export const CONTENT14_3_CONFIRM_ADD_INFO_ACTION = 'CONTENT14_3_CONFIRM_ADD_INFO_ACTION'
export const CONTENT14_3_CONFIRM_ADD_INFO = 'CONTENT14_3_CONFIRM_ADD_INFO'
//编辑和确认更改
export const CONTENT14_3_EDIT_INFO_ACTION = 'CONTENT14_3_EDIT_INFO_ACTION'
export const CONTENT14_3_EDIT_INFO = 'CONTENT14_3_EDIT_INFO'
export const CONTENT14_3_CONFIRM_EDIT_INFO_ACTION = 'CONTENT14_3_CONFIRM_EDIT_INFO_ACTION'
export const CONTENT14_3_CONFIRM_EDIT_INFO = 'CONTENT14_3_CONFIRM_EDIT_INFO'
//确认删除
export const CONTENT14_3_CONFIRM_DELETE_INFO_ACTION = 'CONTENT14_3_CONFIRM_DELETE_INFO_ACTION'
//确认取消
export const CONTENT14_3_CONFIRM_CANCEL_INFO_ACTION = 'CONTENT14_3_CONFIRM_CANCEL_INFO_ACTION'
export const CONTENT14_3_CONFIRM_CANCEL_INFO = 'CONTENT14_3_CONFIRM_CANCEL_INFO'









