//===========================================================================
//common （当多个事件函数相同时，提取公共名称）
//保存当前订单id
export const TO__ORDER_DETAIL__SAVE_ORDER_ID = 'TO__ORDER_DETAIL__SAVE_ORDER_ID'
export const TO__NEW_ORDER__SAVE_ORDER_TRAIN_DATA = 'TO__NEW_ORDER__SAVE_ORDER_TRAIN_DATA'
export const TO__COMPLAIN__SAVE_COMPLAIN_DATA = 'TO__COMPLAIN__SAVE_COMPLAIN_DATA'
export const TO__COMMON__CHANGE_USER_ID = 'TO__COMMON__CHANGE_USER_ID'


//menu
//user_agreement  事件：预定
export const MENU__USER_AGREEMENT__BOOK = 'MENU__USER_AGREEMENT__BOOK'
//select_function  事件：获取版本号，保存版本号，创建订单，保存当前接送的状态
export const MENU__SELECT_FUNCTION__GET_VERSION = 'MENU__SELECT_FUNCTION__GET_VERSION'
export const MENU__SELECT_FUNCTION__SAVE_VERSION = 'MENU__SELECT_FUNCTION__SAVE_VERSION'
export const MENU__SELECT_FUNCTION__CREATE_ORDER = 'MENU__SELECT_FUNCTION__CREATE_ORDER'
export const MENU__SELECT_FUNCTION__SAVE_TRANSFER_TYPE = 'MENU__SELECT_FUNCTION__SAVE_TRANSFER_TYPE'


//place_orders
//choose_train  事件：获取所有列车数据，保存列车数据，选择列车
export const PLACE__CHOOSE_TRAIN__GET_ALL_TRAIN = 'PLACE__CHOOSE_TRAIN__GET_ALL_TRAIN'
export const PLACE__CHOOSE_TRAIN__SAVE_ALL_TRAIN = 'PLACE__CHOOSE_TRAIN__SAVE_ALL_TRAIN'
export const PLACE__CHOOSE_TRAIN__SELECT_TRAIN = 'PLACE__CHOOSE_TRAIN__SELECT_TRAIN'
//search_train  事件：搜索车次，保存查询到的车次列表，扫描车票
export const PLACE__SEARCH_TRAIN__SEARCH_TRAIN = 'PLACE__SEARCH_TRAIN__SEARCH_TRAIN'
export const PLACE__SEARCH_TRAIN__SAVE_TRAIN_LIST = 'PLACE__SEARCH_TRAIN__SAVE_TRAIN_LIST'
export const PLACE__SEARCH_TRAIN__SWEEP_TICKET = 'PLACE__SEARCH_TRAIN__SWEEP_TICKET'
//train_list 事件：选择列车
export const PLACE__TRAIN_LIST__SELECT_TRAIN = 'PLACE__TRAIN_LIST__SELECT_TRAIN'
//new_order_train 事件：获取位置，保存位置，保存联系人，保存手机号,保存车厢号,保存地址（两个）,保存时间，获取时间,保存重要物品，保存车站价格信息
export const PLACE__NEW_ORDER_TRAIN__GET_LOCATION_LIST = 'PLACE__NEW_ORDER_TRAIN__GET_LOCATION_LIST'
export const PLACE__NEW_ORDER_TRAIN__SAVE_LOCATION_LIST = 'PLACE__NEW_ORDER_TRAIN__SAVE_LOCATION_LIST'
export const PLACE__NEW_ORDER_TRAIN__SELECT_END = 'PLACE__NEW_ORDER_TRAIN__SELECT_END'
export const PLACE__NEW_ORDER_TRAIN__SAVE_LOCATION_DATA = 'PLACE__NEW_ORDER_TRAIN__SAVE_LOCATION_DATA'
export const PLACE__NEW_ORDER_TRAIN__SAVE_ARRIVE_TIME_DATA = 'PLACE__NEW_ORDER_TRAIN__SAVE_ARRIVE_TIME_DATA'
export const PLACE__NEW_ORDER_TRAIN__TO_ORDER_INFO = 'PLACE__NEW_ORDER_TRAIN__TO_ORDER_INFO'
export const PLACE__NEW_ORDER_TRAIN__TO_ORDER_PRICE = 'PLACE__NEW_ORDER_TRAIN__TO_ORDER_PRICE'
export const PLACE__NEW_ORDER_TRAIN__RESET_ORDER_PRICE_NUM = 'PLACE__NEW_ORDER_TRAIN__RESET_ORDER_PRICE_NUM'
//new_order_info  事件：获取联系人信息，保存联系人信息，选择联系人，更新联系人
export const PLACE__NEW_ORDER_INFO__GET_CONTACT_INFO = 'PLACE__NEW_ORDER_INFO__GET_CONTACT_INFO'
export const PLACE__NEW_ORDER_INFO__SAVE_CONTACT_INFO = 'PLACE__NEW_ORDER_INFO__SAVE_CONTACT_INFO'
export const PLACE__NEW_ORDER_INFO__UPDATE_CONTACT_INFO = 'PLACE__NEW_ORDER_INFO__UPDATE_CONTACT_INFO'
export const PLACE__NEW_ORDER_INFO__UPDATE_NEW_ORDER_TRAIN = 'PLACE__NEW_ORDER_INFO__UPDATE_NEW_ORDER_TRAIN'
export const PLACE__NEW_ORDER_INFO__DELETE_CONTACT_INFO = 'PLACE__NEW_ORDER_INFO__DELETE_CONTACT_INFO'

//new_order_price 事件：获取商品列表，保存商品列表，保存乘车人数，保存行李件数，保存是否送上车厢，保存用户检查信息
export const PLACE__NEW_ORDER_PRICE__GET_GOODS_LIST = 'PLACE__NEW_ORDER_PRICE__GET_GOODS_LIST'
export const PLACE__NEW_ORDER_PRICE__SAVE_GOODS_LIST = 'PLACE__NEW_ORDER_PRICE__SAVE_GOODS_LIST'
export const PLACE__NEW_ORDER_PRICE__SAVE_RIDER_NUM = 'PLACE__NEW_ORDER_PRICE__SAVE_RIDER_NUM'
export const PLACE__NEW_ORDER_PRICE__SAVE_LUGGAGE_NUM = 'PLACE__NEW_ORDER_PRICE__SAVE_LUGGAGE_NUM'
export const PLACE__NEW_ORDER_PRICE__SAVE_SMALL_LUGGAGE_NUM = 'PLACE__NEW_ORDER_PRICE__SAVE_SMALL_LUGGAGE_NUM'
export const PLACE__NEW_ORDER_PRICE__SAVE_INCARRIAGE_VALUE = 'PLACE__NEW_ORDER_PRICE__SAVE_INCARRIAGE_VALUE'
export const PLACE__NEW_ORDER_PRICE__SAVE_ROOM = 'PLACE__NEW_ORDER_PRICE__SAVE_ROOM'
export const PLACE__NEW_ORDER_PRICE__SAVE_WAIT_CHECK_DATA = 'PLACE__NEW_ORDER_PRICE__SAVE_WAIT_CHECK_DATA'
//wait_check 事件：提交订单submit order
export const PLACE__WAIT_CHECK__SUBMIT_ORDER = 'PLACE__WAIT_CHECK__SUBMIT_ORDER'
export const PLACE__WAIT_CHECK__SAVE_WAIT_ACCEPTANCE_DATA = 'PLACE__WAIT_CHECK__SAVE_WAIT_ACCEPTANCE_DATA'

//manage_orders
//order_list 事件：获取订单列表，保存订单列表，删除订单，取消订单，更新订单，完成订单，去评价，查看评价，查看订单
export const MANAGE__ORDER_LIST__SET_ORDER_TYPE = 'MANAGE__ORDER_LIST__SET_ORDER_TYPE'
export const MANAGE__ORDER_LIST__GET_ORDER_LIST = 'MANAGE__ORDER_LIST__GET_ORDER_LIST'
export const MANAGE__ORDER_LIST__SAVE_ORDER_LIST = 'MANAGE__ORDER_LIST__SAVE_ORDER_LIST'
export const MANAGE__ORDER_LIST__DELETE_ORDER = 'MANAGE__ORDER_LIST__DELETE_ORDER'
export const MANAGE__ORDER_LIST__CANCEL_ORDER = 'MANAGE__ORDER_LIST__CANCEL_ORDER'
export const MANAGE__ORDER_LIST__UPDATE_ORDER = 'MANAGE__ORDER_LIST__UPDATE_ORDER'
export const MANAGE__ORDER_LIST__COMPLETE_ORDER = 'MANAGE__ORDER_LIST__COMPLETE_ORDER'
export const MANAGE__ORDER_LIST__TO_JUDGE = 'MANAGE__ORDER_LIST__TO_JUDGE'
export const MANAGE__ORDER_LIST__TO_JUDGE_ORDER_ID = 'MANAGE__ORDER_LIST__TO_JUDGE_ORDER_ID'
export const MANAGE__ORDER_LIST__JUDGE_DETAIL = 'MANAGE__ORDER_LIST__JUDGE_DETAIL'
export const MANAGE__ORDER_LIST__JUDGE_DETAIL_ORDER_ID = 'MANAGE__ORDER_LIST__JUDGE_DETAIL_ORDER_ID'
export const MANAGE__ORDER_LIST__ORDER_DETAIL = 'MANAGE__ORDER_LIST__ORDER_DETAIL'
//order_detail 事件：获取订单信息，保存商品列表，删除订单，取消订单，更新订单，完成订单，去投诉
export const MANAGE__ORDER_DETAIL__GET_ORDER_DETAIL = 'MANAGE__ORDER_DETAIL__GET_ORDER_DETAIL'
export const MANAGE__ORDER_DETAIL__SAVE_ORDER_DETAIL = 'MANAGE__ORDER_DETAIL__SAVE_ORDER_DETAIL'
export const MANAGE__ORDER_DETAIL__SAVE_GOODS_LIST = 'MANAGE__ORDER_DETAIL__SAVE_GOODS_LIST'
export const MANAGE__ORDER_DETAIL__SAVE_POINT_LIST = 'MANAGE__ORDER_DETAIL__SAVE_POINT_LIST'
export const MANAGE__ORDER_DETAIL__DELETE_ORDER = 'MANAGE__ORDER_DETAIL__DELETE_ORDER'
export const MANAGE__ORDER_DETAIL__CANCEL_ORDER = 'MANAGE__ORDER_DETAIL__CANCEL_ORDER'
export const MANAGE__ORDER_DETAIL__UPDATE_ORDER = 'MANAGE__ORDER_DETAIL__UPDATE_ORDER'
export const MANAGE__ORDER_DETAIL__COMPLETE_ORDER = 'MANAGE__ORDER_DETAIL__COMPLETE_ORDER'
export const MANAGE__ORDER_DETAIL__TO_COMPLAIN = 'MANAGE__ORDER_DETAIL__TO_COMPLAIN'
export const MANAGE__ORDER_DETAIL__TO_MAP = 'MANAGE__ORDER_DETAIL__TO_MAP'
//judge 事件：获取接送小哥信息，保存信息，更新评价信息，更新星级，添加标签，减少标签,提交评价
export const MANAGE__JUDGE__GET_STAFF_LIST = 'MANAGE__JUDGE__GET_STAFF_LIST'
export const MANAGE__JUDGE__SAVE_STAFF_LIST = 'MANAGE__JUDGE__SAVE_STAFF_LIST'
export const MANAGE__JUDGE__UPDATE_RATE_CONTENT = 'MANAGE__JUDGE__UPDATE_RATE_CONTENT'
export const MANAGE__JUDGE__UPDATE_STAR_LEVEL = 'MANAGE__JUDGE__UPDATE_STAR_LEVEL'
export const MANAGE__JUDGE__ADD_TAG_NAMEL = 'MANAGE__JUDGE__ADD_TAG_NAMEL'
export const MANAGE__JUDGE__DELETE_TAG_NAME = 'MANAGE__JUDGE__DELETE_TAG_NAME'
export const MANAGE__JUDGE__SUBMIT = 'MANAGE__JUDGE__SUBMIT'
//judge_detail 事件：获取评价信息，保存评价信息
export const MANAGE__JUDGE_DETAIL__GET_RATE_DETAIL = 'MANAGE__JUDGE_DETAIL__GET_RATE_DETAIL'
export const MANAGE__JUDGE_DETAIL__SAVE_RATE_DETAIL = 'MANAGE__JUDGE_DETAIL__SAVE_RATE_DETAIL'
//complain 事件：保存最大长度和内容，保存订单编号，保存姓名，保存联系电话，提交投诉
export const MANAGE__COMPLAIN__SUBMIT_COMPLAIN = 'MANAGE__COMPLAIN__SUBMIT_COMPLAIN'
//complainList 事件：获取投诉列表，保存投诉列表，去订单投诉
export const MANAGE__COMPLAIN_LIST__GET_COMPLAIN_LIST = 'MANAGE__COMPLAIN_LIST__GET_COMPLAIN_LIST'
export const MANAGE__COMPLAIN_LIST__SAVE_COMPLAIN_LIST = 'MANAGE__COMPLAIN_LIST__SAVE_COMPLAIN_LIST'
export const MANAGE__COMPLAIN_LIST__SAVE_COMPLAIN_DATA = 'MANAGE__COMPLAIN_LIST__SAVE_COMPLAIN_DATA'
export const MANAGE__COMPLAIN_LIST__SAVE_USER_ID = 'MANAGE__COMPLAIN_LIST__SAVE_USER_ID'















